name: ServerCore
main: Aleondev\Main
version: 1.0.0
api: 
- 3.0.0
- 4.0.0
load: POSTWORLD
author: Aleondev
description: "ServerCore by Aleondev"

commands:
  tpall:
    description: §e[Core]§btpall
    permission: tpall.core
  tpohere:
    description: §e[Core]§bTpohere
    permission: tpohere.core
  gm:
    description: §e[Core]§bGM
    permission: gm.core
  tag:
    description: §e[Core]§bTag
    permission: tag.core
  nacht:
    description: §e[Core]§bNacht
    permission: nacht.core
  flyon:
    description: §e[Core]§bFlyon
    permission: flyon.core
  flyoff:
    description: §e[Core]§bFlyoff
    permission: flyoff.core
